pxbot/dashboard/urls.py
from django.urls import path
from django.views import generic
from . import views
from .views import DashView, UserView, UserEditView, UserCreateView


app_name = 'dashboard'
urlpatterns =[
    path('', DashView.as_view(), name='index'),
    path('users/', UserView.as_view(), name='users'),
    path('users/<int:pk>/', UserEditView.as_view(), name='users'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('automation/', views.selenium_automation, name='automation'),
    path('expiration/', views.expiration, name='expiration')
]

pxbot/pxbot/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = {
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    re_path('^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
}

pxbot/dashboard/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=30, null=False)
    password = models.CharField(max_length=255, null=False)
    is_active = models.BooleanField(default=True)
    expiration = models.DateField(null=False)
    member_id = models.CharField(max_length=10, null=False)
    deposit = models.DecimalField(max_digits=16, decimal_places=2, default=0.0)
    payout = models.DecimalField(max_digits=16, decimal_places=2, default=0.0)
    earnings = models.DecimalField(max_digits=16, decimal_places=2, default=0.0)
    total_earned = models.DecimalField(max_digits=16, decimal_places=2, default=0.0)
    px_expiration = models.CharField(max_length=50, default="Never")

    def __str__(self):
        return self.username

LOGS_CHOICES = (
    ("INFO", "INFO"),
    ("WARNING", "WARNING"),
    ("ERROR", "ERROR")
)


class TransactionLog(models.Model):
    log_date = models.DateTimeField(auto_now_add=True)
    log_message = models.TextField(null=False)
    type = models.CharField(choices=LOGS_CHOICES, max_length=30)

    def __str__(self):
        return self.log_message[:50]

class Config(models.Model):
    loading_time_in_min = models.IntegerField(default=60)


    def __str__(self):
        return "CONFIG"

# def encryption():
    # from cryptography.fernet import Fernet
    # key = Fernet.generate_key()
    # cipher_suite = Fernet(key)
    # cipher_text = cipher_suite.encrypt(b"A really secret message. Not for prying eyes.")
    # plain_text = cipher_suite.decrypt(cipher_text)

pxbot/dashboard/forms.py
from django.forms import ModelForm, SelectDateWidget, CheckboxInput
from django import forms

from .models import User

ATTRS_PASS = {'type': 'password'}
ATTRS_DATE = {'class': 'datepicker', 'readonly':''}


class UserUpdateActiveForm(ModelForm):
    class Meta:
        model = User
        fields = ('is_active',)


class UserEditForm(ModelForm):
    password = forms.CharField(widget=forms.TextInput(attrs=ATTRS_PASS))
    expiration = forms.DateField(widget=forms.TextInput(attrs=ATTRS_DATE))
    px_expiration = forms.CharField(widget=forms.TextInput(attrs={'readonly':''}))

    class Meta:
        model = User
        fields = (
            'username',
            'password',
            'expiration',
            'px_expiration'
        )


class UserCreateForm(ModelForm):
    password = forms.CharField(widget=forms.TextInput(attrs=ATTRS_PASS))
    expiration = forms.DateField(widget=forms.TextInput(attrs=ATTRS_DATE))

    class Meta:
        model = User
        fields = (
            'username',
            'password',
            'expiration',
        )

pxbot/dashboard/views.py
import datetime

from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View, generic
from django.contrib import messages

from .models import User
from .forms import UserCreateForm, UserEditForm, UserUpdateActiveForm
from .crawler import pxbot as px

import logging

logger = logging.getLogger(__name__)


class DashView(View):
    def get(self, request):
        total_users = User.objects.count()
        total_active = User.objects.filter(is_active=True).count()
        total_inactive = User.objects.filter(is_active=False).count()

        top_earners = User.objects.order_by('-total_earned')[:5]
        ready_for_buying = User.objects.order_by('-payout')[:5]
        near_expiration = User.objects.order_by('-expiration')[:5]
        # near_px_expiration = User.objects.order_by('-px_expiration')[:5]
        px_expirations = User.objects.filter(px_expiration="Never")[:5]

        return render(request, 'dashboard/index.html', {'header': 'Admin dashboard', 'total_users': total_users,
                                                        'total_inactive': total_inactive, 'total_active': total_active,
                                                        'top_earners': top_earners, 'ready_for_buying': ready_for_buying,
                                                        'near_expiration': near_expiration, 'near_px_expiration': px_expirations})


class UserView(generic.ListView):
    model = User
    paginate_by = 10
    template_name = 'dashboard/users.html'

    def get_queryset(self):
        return User.objects.all().order_by('username')

    def post(self, request):
        id = request.POST['user_id']
        instance = User.objects.get(id=id)
        form = UserUpdateActiveForm(request.POST, instance=instance)

        if form.is_valid():
            is_active_inst = form.save()
            is_active_inst.save()
            return HttpResponseRedirect(reverse("dashboard:users"))
        return HttpResponseRedirect("")


class UserEditView(generic.edit.UpdateView):
    model = User
    form_class = UserEditForm
    template_name = 'dashboard/user_update_form.html'

    def get_success_url(self):
        return reverse("dashboard:users")

    def form_invalid(self, form):
        return HttpResponseRedirect("")


class UserCreateView(generic.edit.CreateView):
    model = User
    form_class = UserCreateForm
    template_name = 'dashboard/user_form.html'

    def post(self, request, *args, **kwargs):
        form = UserCreateForm(request.POST)
        messages.success(request, "Done!")
        if form.is_valid():
            user = form.save()
            user.save()
            return HttpResponseRedirect(reverse("dashboard:users"))
        return HttpResponseRedirect("")


def selenium_automation(request):
    # try:
    #     users = User.objects.filter(is_active=True)
    # except User.DoesNotExist:
    #     return HttpResponseRedirect(reverse("dashboard:index"))
    #
    # pxbot = px.Pxbot()
    # wallet = 'payout'
    #
    # for user in users:
    #     if pxbot.authenticate(user.username, user.password):
    #         metrics = pxbot.init_update()
    #         if metrics['expired'] != "Never":
    #             while metrics['earnings'] + metrics[wallet] >= 10.0:
    #                 if 'successfully' in pxbot.transfer_finance(metrics['earnings'], wallet):
    #                     metrics['earnings'] -= 10
    #                     pxbot.buy_revshares(wallet)
    #
    #         elif metrics['expired'] == "Never":
    #             while metrics['earnings'] >= 25:
    #                 if 'successfully' in pxbot.transfer_finance(25, wallet):
    #                     metrics['earnings'] -= 25
    #                     pxbot.upgrade_membership(wallet)
    #
    #         user.deposit = metrics['deposit']
    #         user.payout = metrics['payout']
    #         user.earnings = metrics['earnings']
    #         user.total_earned = metrics['total_earned']
    #         user.px_expiration = metrics['expired']
    #         user.save()
    #         pxbot.end()
    #     else:
    #         print("User does not exist: {}".format(user.username))

    return HttpResponseRedirect(reverse("dashboard:index"))


def expiration(request):
    for user in User.objects.filter(is_active=True):
        print(datetime.date.today())
        print(user.expiration)
        if datetime.date.today() >= user.expiration:
            user.is_active = False
            user.save()

    return HttpResponseRedirect(reverse("dashboard:index"))

pxbot/dashboard/templates/dashboard/base.html
<html>
    <head>
        {% load static %}
        <title>PreneurBot</title>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'dashboard/materialize/css/materialize.min.css' %}">
        <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'dashboard/css/nav.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        {% block content %}
        {% endblock %}
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="{% static 'dashboard/materialize/js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'dashboard/js/init.js' %}"></script>
        <script type="text/javascript" src="{% static 'dashboard/js/script.js' %}"></script>
    </body>
</html>

pxbot/dashboard/templates/dashboard/cards.html
<div class="row">
   <div class="col s12 m3">
      <div class="card card1">
         <div class="card-content white-text">
            <span class="card-title" id="count-down">00:00:00
            </span>
            <p>Till next run
            </p>
         </div>
      </div>
   </div>
   <div class="col s12 m3">
      <div class="card card2">
         <div class="card-content white-text">
            <span class="card-title">{{ total_users }}
            </span>
            <p>Total users
            </p>
         </div>
      </div>
   </div>
   <div class="col s12 m3">
      <div class="card card3">
         <div class="card-content white-text">
            <span class="card-title">{{ total_inactive }}
            </span>
            <p>Total inactive users
            </p>
         </div>
      </div>
   </div>
   <div class="col s12 m3">
      <div class="card card4">
         <div class="card-content white-text">
            <span class="card-title">{{ total_active }}
            </span>
            <p>Total active users
            </p>
         </div>
      </div>
   </div>
</div>

pxbot/dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% block content %}

{% include 'dashboard/nav.html' %}
{% include 'dashboard/cards.html' %}

<div class="row">
   <div class="col s12 m6 table-div">
      <h5 style="color: #459A5E">Top Earners</h5>
      <hr>
      <div class="shadow">

      <table class="striped">
         <thead>
            <tr>
               <th>Username</th>
               <th>Total money earned</th>
            </tr>
         </thead>
         <tbody>
            {% for user in top_earners %}
            <tr>
               <td>{{ user.username }}</td>
               <td>$ {{ user.total_earned }}</td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
      </div>
   </div>

   <div class="col s12 m6 table-div">
      <h5>Ready for buying</h5>
      <hr>
      <div class="shadow">

         <table class="striped">
            <thead>
               <tr>
                  <th>Username</th>
                  <th>Earnings balance</th>
               </tr>
            </thead>
            <tbody>
            {% for user in ready_for_buying %}
               <tr>
                  <td>{{ user.username }}</td>
                  <td>$ {{ user.earnings }}</td>
               </tr>
            {% endfor %}
            </tbody>
         </table>
      </div>
   </div>
</div>



<div class="row">
   <div class="col s12 m6  table-div">
      <h5 style="color: #E84F38;">Near payment expiration</h5>
      <hr>
      <div class="shadow">

         <table class="striped">
            <thead>
               <tr>
                  <th>Username</th>
                  <th>Expiration</th>
               </tr>
            </thead>
            <tbody>
            {% for user in near_expiration %}
               <tr>
                  <td>{{ user.username }}</td>
                  <td>{{ user.expiration }}</td>
               </tr>
            {% endfor %}
            </tbody>
         </table>
      </div>
   </div>
   <div class="col s12 m6  table-div">
      <h5 style="color: #F9CA3A;">Expired PreneurX memberships</h5>
      <hr>
      <div class="shadow">

         <table class="striped">
            <thead>
               <tr>
                  <th>Username</th>
                  <th>Expires after</th>
               </tr>
            </thead>
            <tbody>
             {% for user in px_expirations %}
               <tr>
                  <td>{{ user.username }}</td>
                  <td>{{ user.px_expiration }}</td>
               </tr>
            {% endfor %}
            </tbody>
         </table>
      </div>
   </div>
</div>

{% endblock %}

pxbot/dashboard/templates/dashboard/nav.html
{% load static %}
<ul id="slide-out" class="sidenav sidebar">
   <li>
      <div class="user-view">
         <a href="#user"><img class="circle" src="{% static 'dashboard/image/user.jpg' %}"></a>
         <a href="#name"><span class="white-text name"> <b>Admin</b> </span></a>
         <a href="#email"><span class="white-text email"></span></a>
      </div>
   </li>
   <li><div class="divider"></div></li>
   <li><a href="{% url 'dashboard:users' %}"><i class="material-icons">supervised_user_circle</i>User Management</a></li>
   <li><a href="#!"><i class="material-icons">settings_applications</i>Automation Management</a></li>
   <li><a href="#!"><i class="material-icons">notes</i>Logs</a></li>
</ul>
<div class="row top-nav shadow">
    <div class="col s10 nav-header">
       <a href="{% url 'dashboard:index' %}"><h5> <b> {{ header }} </b> </h5></a>
    </div>
     <div data-target="slide-out" class="sidenav-trigger col s2">
         <a href="#" class="sidenav-trigger-div ">
            <img class="circle sidenav-trigger-icon" src="{% static 'dashboard/image/user.jpg' %}">
            Admin
         </a>
    </div>
</div>

pxbot/dashboard/templates/dashboard/user_form.html
{% extends 'dashboard/base.html' %}
{% block content %}

{% include 'dashboard/nav.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/css/user.css' %}">
<div class="container ">
    <div class="row">
        <a href="{% url 'dashboard:users' %}" id="btn-back" class="waves-effect waves-light btn"><i class="material-icons left">arrow_back</i>Back</a>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="div-form shadow">
        <h5 class="module-title">Add new user</h5>
        <br>
        <form method="post">{% csrf_token %}
            {{ form.as_table }}
            <button class="btn waves-effect waves-light btn-add-user" type="submit" id="submit-user" name="action">Submit
                  <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>
{% endblock %}

pxbot/dashboard/templates/dashboard/user_update_form.html
{% extends 'dashboard/base.html' %}
{% block content %}

{% include 'dashboard/nav.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/css/user.css' %}">
<div class="container ">
    <div class="row">
        <a href="{% url 'dashboard:users' %}" id="btn-back" class="waves-effect waves-light btn"><i class="material-icons left">arrow_back</i>Back</a>
    </div>
    <div class="div-form shadow">
        <h5 class="module-title">Update user</h5>
        <br>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <button class="btn waves-effect waves-light btn-add-user" type="submit" id="submit-user" name="action" value="Update">Submit
                  <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>

{% endblock %}

pxbot/dashboard/templates/dashboard/users.html
{% extends 'dashboard/base.html' %}

{% block content %}

{% include 'dashboard/nav.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/css/user.css' %}">

<div class="container ">
    <div class="row">

        <a href="{% url 'dashboard:index' %}" id="btn-back" class="waves-effect waves-light btn"><i class="material-icons left">arrow_back</i>Back</a>
        <a href="{% url 'dashboard:create' %}" class="waves-effect waves-light btn btn-add-user"><i class="material-icons left">add</i>add user</a>
    </div>
    <br>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="shadow div-form">

        <table class="striped table-users">
        <thead>
            <tr>
                <td>User</td>
                <td>PreneurX expiration</td>
                <td>Payment expiration</td>
            </tr>
        </thead>
        <tbody>
                {% for article in object_list %}
                    <tr>
                        <td><a href="{% url 'dashboard:users' article.id %}"> {{ article.username }} </a> </td>
                        <td>{{ article.px_expiration }}</td>
                        <td>{{ article.expiration }}</td>
                        <td>
                            <div class="switch">
                                <form method="post" id="form-update-active" >{% csrf_token %}
                                    <input hidden name="user_id" id = "user_id" value="{{ article.id }}">
                                    <label>
                                    Inactive
                                    {% if article.is_active == False %}
                                    <input class="check-active" id="is_active_{{article.id}}" name="is_active" type="checkbox" value="False"">
                                    {% else %}
                                    <input class="check-active" id="is_active_{{article.id}}" name="is_active" checked type="checkbox" value="True"">
                                    {% endif %}
                                    <span class="lever"></span>
                                    Active
                                </label>
                                </form>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
        </tbody>
        </table>
    </div>



</div>


{% endblock %}